1. Crie um array de floats com 10 elementos positivos e negativos entre 0 e 1. Em seguida, multiplique seus valores por 100 e crie um novo vetor apenas com a parte inteira destes números. (use seed(5) antes)

In [3]:
import numpy as np
import random

In [31]:
np.random.seed(5)

array = np.random.randn(10)
print(array)

new_array = array * 100
print(new_array)


[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984  1.58248112
 -0.9092324  -0.59163666  0.18760323 -0.32986996]
[ 44.12274869 -33.08701519 243.0771187  -25.20921296  10.96098416
 158.24811171 -90.92324049 -59.16366579  18.76032258 -32.98699578]


In [28]:
vetor = []
tam = len(new_array)
for i in range (0, tam):
  vetor.append(int(new_array[i]))

vetor

[44, -33, 243, -25, 10, 158, -90, -59, 18, -32]

2. Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros entre 1 e 50; (use seed(10) antes)

In [35]:
np.random.seed(10)
matriz = np.random.randint(0, 51, size=(4,4))
matriz

array([[ 9, 36, 15,  0],
       [49, 28, 25, 29],
       [48, 29, 49,  8],
       [ 9,  0, 42, 40]])

3. Mostre o resultado da média de cada linha e cada coluna da matriz gerada pela questão 2, em seguida, apresente o maior valor das médias para as linhas e também para as colunas;

In [43]:
rows = np.mean(matriz, axis=1)   #calcula média de cada linha
print(rows)



[15.   32.75 33.5  22.75]


In [50]:
avg_rows = []

for j, k in enumerate(rows):
  avg_rows.append(k)
  print(f'Media da linha {j + 1}: {k}')     #add 1 ao j para não começar no indice 0

print(avg_rows)

Media da linha 1: 15.0
Media da linha 2: 32.75
Media da linha 3: 33.5
Media da linha 4: 22.75
[15.0, 32.75, 33.5, 22.75]


In [51]:
columns = np.mean(matriz, axis=0)   #calcula média de cada coluna
print(columns)



[28.75 23.25 32.75 19.25]


In [49]:
avg_columns = []

for j, k in enumerate(columns):
  avg_columns.append(k)
  print(f'Media da linha {j + 1}: {k}')

print(avg_columns)

[28.75 23.25 32.75 19.25]
Media da linha 1: 28.75
Media da linha 2: 23.25
Media da linha 3: 32.75
Media da linha 4: 19.25
[28.75, 23.25, 32.75, 19.25]


In [52]:
max_row = max(avg_rows)
max_column = max(avg_columns)

print(max_row)
print(max_column)

33.5
32.75


4. Baseando na matriz gerada na questão 2, mostre a quantidade de aparições de cada um dos números na mesma. Em seguida, mostre apenas os números que aparecem duas vezes.

In [57]:
import collections    #armazena coleções de dados num dicionário
matriz

array([[ 9, 36, 15,  0],
       [49, 28, 25, 29],
       [48, 29, 49,  8],
       [ 9,  0, 42, 40]])

In [55]:
matriz_uni = (np.asarray(matriz)).flatten()
matriz_uni


array([ 9, 36, 15,  0, 49, 28, 25, 29, 48, 29, 49,  8,  9,  0, 42, 40])

In [61]:
aparicoes = collections.Counter(matriz_uni)
aparicoes

Counter({0: 2,
         8: 1,
         9: 2,
         15: 1,
         25: 1,
         28: 1,
         29: 2,
         36: 1,
         40: 1,
         42: 1,
         48: 1,
         49: 2})

In [78]:
for  k,v in aparicoes.items():
  print(f'o número {k} aparece {v} vezes')



o número 9 aparece 2 vezes
o número 36 aparece 1 vezes
o número 15 aparece 1 vezes
o número 0 aparece 2 vezes
o número 49 aparece 2 vezes
o número 28 aparece 1 vezes
o número 25 aparece 1 vezes
o número 29 aparece 2 vezes
o número 48 aparece 1 vezes
o número 8 aparece 1 vezes
o número 42 aparece 1 vezes
o número 40 aparece 1 vezes


In [79]:
for k, v in aparicoes.items():
  if v == 2:
    print(f'o número {k}, apareceu 2 vezes')

o número 9, apareceu 2 vezes
o número 0, apareceu 2 vezes
o número 49, apareceu 2 vezes
o número 29, apareceu 2 vezes
