In [16]:
import pandas as pd
import numpy as np

1. Crie um array de tamanho 30 com valores igualmente espaçados entre 0 e 1;

In [18]:
np.linspace(0, 1, 30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

2. Crie dois arrays: um de números pares de 0 a 51 e outros também de pares de 100 à 50.Em seguida, os concatene e mostre os resultados ordenados;

In [19]:
x = np.arange(0, 51, 2)  

y = np.arange(100, 50, -2)

print(x)
print(y)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52]


In [26]:
z = np.concatenate((x, y))
z

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
       100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52])

3. Ordene os resultados do array da resultante da questão 2 em ordem crescente;

In [28]:
z.sort()
z

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

4. Crie uma matriz formada somente por uns de tamanho 3x4. Em seguida, transforme-a em um array de uma dimensão.

In [37]:
matriz = np.ones((3,4))
array = (np.asarray(matriz)).flatten()   #converte array N dimensional em unidimensional
print(matriz)
print(array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5. Crie uma matriz de tamanho qualquer. Extraia seu número de linhas e colunas, multiplique-os, e diga se esta matriz poderia se tornar um vetor com número par ou ímpar de elementos.

In [52]:
tamanho1 = (3, 4)
tamanho2 = (3, 5) 
matriz = np.ones((tamanho1))
matriz


tupla = matriz.shape
produto = tupla[0] * tupla[1]
if produto % 2 ==0:
  print('Número par de elementos:', produto)
else:
  print('Número impar de elementos:', produto)

Número par de elementos: 12
